- name: NODEJS - Add GPG Nodesource GPG Key
  become: true
  shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

- name: NODEJS - Installa package
  become: true
  apt:
    name: nodejs
    state: latest
    update_cache: yes
